# Generated by Django 5.1.6 on 2025-04-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_delete_review_remove_useractivity_property_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.CharField(max_length=20),
        ),
    ]
